### ISSUE TITLE
Develop means of storing minimally-structured (YAML?) data for each language

### ISSUE THREAD

**Issue by timjore** [unfoldingWord-box3/td#1]
the data for each language should be:

- [x] extensible, so that new fields can be added easily where needed but not required
- [x] rendered in a user-friendly view online and in the exported data (e.g., PDF, EPUB)
- [x] exportable by scripts to generate the API content in needed data formats (e.g., JSON, CSV)

**Comment by jag3773** [comment]
This task I'm closing as we have the basic framework in place.  More detailed work on exactly how to represent the data will happen in #5 .
